main:
  required_status_checks:
    strict: true
    contexts: [ 'triage' ]
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismissal_restrictions: 
      users: [ 'philltew' ]
      teams: [ ]
  restrictions: null
  enforce_admins: true
  allow_force_pushes: false
  allow_deletions: false
  required_conversation_resolution: false
