name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Changes
  $CHANGES

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: 'ðŸ˜š Breaking Changes'
    labels:
      - 'breaking'
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'ðŸ”§ Maintenance'
    label: 
      - 'chore'
      - 'automation'
  - title: 'ðŸ“ Documentaion'
    label: 
      - 'docs'
      
autolabeler:

  - label: 'docs'
    files:
      - '*.md'      
    title:
      - '/^ðŸ“/i'      
      
  - label: 'automation'
    files:
      - '.github/**/*'
    title:
      - '/^ðŸ”§/i'
      
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^ðŸ›/i'
      - '/^ðŸŒ/i'
      - '/^ðŸ/i'
      - '/^ðŸœ/i'
      - '/^ðŸž/i'
      - '/^ðŸ¦—/i'
      - '/^ðŸ¦‹/i'
      - '/^ðŸ•·ï¸/i'
      
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/^âœ¨/i'
  
  - label: 'breaking'
    title:
      - '/^ðŸ’£/i'      
      
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'workflow'
      - 'docs'
      - 'security'

exclude-labels:
  - 'skip-changelog'
