name-template: '🚀 v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # Changes
  $CHANGES

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

categories:
  - title: '💣 Breaking Changes'
    labels:
      - 'breaking'
  - title: '😚 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🔧 Maintenance'
    label: 
      - 'chore'
      - 'automation'
  - title: '📝 Documentaion'
    label: 
      - 'docs'
      
autolabeler:

  - label: 'docs'
    files:
      - '*.md'      
    title:
      - '/^📝/i'      
      
  - label: 'automation'
    files:
      - '.github/**/*'
    title:
      - '/^🔧/i'
      - '/^🛠️/i'
      - '/^⛏️/i'
      
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^🐛/i'
      - '/^🐌/i'
      - '/^🐝/i'
      - '/^🐜/i'
      - '/^🐞/i'
      - '/^🦗/i'
      - '/^🦋/i'
      - '/^🕷️/i'
      
  - label: 'feature'
    branch:
      - '/feature\/.+/'
    title:
      - '/^✨/i'
      - '/^😗/i'
      - '/^😚/i'
      - '/^😘/i'
      - '/^😙/i'
      - '/^💎/i'
  
  - label: 'breaking'
    title:
      - '/^💣/i'      
      
  - label: 'security'
    title:
      - '/^🛡️/i'    
      - '/^🔒/i'   
      - '/^🔐/i'   
      
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'automation'
      - 'docs'
      - 'security'

exclude-labels:
  - 'skip-changelog'
