name: Restore Simple FS Cache
description: 'Cache for self hosted runners'
inputs:
  key:
    description: ''
    required: true

  fallback:
    description: ''
    required: true

  path:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
  - name: Restore Simple Cache
    env:
      IN_KEY: ${{ inputs.key }}
      IN_FALLBACK: ${{ inputs.fallback }}
      IN_PATH: ${{ inputs.path }}
    shell: bash
    run: |
      #!/bin/bash

      cache1="../cache/$IN_FALLBACK"
      cache2="../cache/$IN_KEY"
      path="$IN_PATH"

      if [ -d $cache2 ]
      then
        cp -r $cache2 $path 2> /dev/null

        if [ $? -eq 0 ]
        then
          echo "Restored cache from $cache2"
        else
          echo "Could not restore cache from $cache2" >&2
        fi

      else
        if [ -d $cache1 ]
        then
          cp -r $cache1 $path 2> /dev/null

          if [ $? -eq 0 ]
          then
            echo "Restored cache from $cache1"
          else
            echo "Could not restore cache from $cache1" >&2
          fi
        else
          echo "No cache exists"
        fi
      fi

      if [ -d $path ]; then ls --format=single-column $path; fi
